language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -r requirements.txt -r requirements-dev.txt -e .
  - pip install coverage coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib; fi"

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

services:
  - mongodb

script: py.test --cov flask_security --cov-report term-missing --pep8 --flakes

after_script:
  - coveralls
